package JFRAMES;
/**
 * @author cesar
 */
public class Calculadora extends javax.swing.JFrame {
    
    AlmacenNumeros numero = new AlmacenNumeros();
    int num1;
    int num2;
    
    String signo;
    

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MostrarNumeros = new javax.swing.JTextArea();
        panelResultado = new javax.swing.JPanel();
        labelResultado = new javax.swing.JLabel();
        PanelBoton7 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        panelBoton9 = new javax.swing.JPanel();
        label9 = new javax.swing.JLabel();
        panelBoton4 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        panelBoton5 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        panelBoton8 = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        panelBoton2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        panelBoton3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        panelBoton1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        panelBoton0 = new javax.swing.JPanel();
        label0 = new javax.swing.JLabel();
        panelBoton6 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        panelResta = new javax.swing.JPanel();
        labelResta = new javax.swing.JLabel();
        panelMultiplicacion = new javax.swing.JPanel();
        labelMultiplicacion = new javax.swing.JLabel();
        panelDivision = new javax.swing.JPanel();
        labelDivision = new javax.swing.JLabel();
        panelSuma = new javax.swing.JPanel();
        labelSuma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(32, 32, 32));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MostrarNumeros.setColumns(20);
        MostrarNumeros.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        MostrarNumeros.setRows(5);
        jScrollPane1.setViewportView(MostrarNumeros);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 630, 180));

        panelResultado.setBackground(new java.awt.Color(64, 60, 60));

        labelResultado.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(255, 255, 255));
        labelResultado.setText("   =");
        labelResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelResultadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 80, 80));

        PanelBoton7.setBackground(new java.awt.Color(64, 60, 60));
        PanelBoton7.setForeground(new java.awt.Color(255, 255, 255));

        label7.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("   7");
        label7.setVerifyInputWhenFocusTarget(false);
        label7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBoton7Layout = new javax.swing.GroupLayout(PanelBoton7);
        PanelBoton7.setLayout(PanelBoton7Layout);
        PanelBoton7Layout.setHorizontalGroup(
            PanelBoton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBoton7Layout.setVerticalGroup(
            PanelBoton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(PanelBoton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 80, 80));

        panelBoton9.setBackground(new java.awt.Color(64, 60, 60));

        label9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("   9");
        label9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton9Layout = new javax.swing.GroupLayout(panelBoton9);
        panelBoton9.setLayout(panelBoton9Layout);
        panelBoton9Layout.setHorizontalGroup(
            panelBoton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoton9Layout.createSequentialGroup()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBoton9Layout.setVerticalGroup(
            panelBoton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        panelBoton4.setBackground(new java.awt.Color(64, 60, 60));

        label4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("   4");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton4Layout = new javax.swing.GroupLayout(panelBoton4);
        panelBoton4.setLayout(panelBoton4Layout);
        panelBoton4Layout.setHorizontalGroup(
            panelBoton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelBoton4Layout.setVerticalGroup(
            panelBoton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        panelBoton5.setBackground(new java.awt.Color(64, 60, 60));

        label5.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("   5");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton5Layout = new javax.swing.GroupLayout(panelBoton5);
        panelBoton5.setLayout(panelBoton5Layout);
        panelBoton5Layout.setHorizontalGroup(
            panelBoton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelBoton5Layout.setVerticalGroup(
            panelBoton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        panelBoton8.setBackground(new java.awt.Color(64, 60, 60));
        panelBoton8.setForeground(new java.awt.Color(255, 255, 255));

        label8.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("   8");
        label8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton8Layout = new javax.swing.GroupLayout(panelBoton8);
        panelBoton8.setLayout(panelBoton8Layout);
        panelBoton8Layout.setHorizontalGroup(
            panelBoton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBoton8Layout.setVerticalGroup(
            panelBoton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, 80));

        panelBoton2.setBackground(new java.awt.Color(64, 60, 60));

        label2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("   2");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton2Layout = new javax.swing.GroupLayout(panelBoton2);
        panelBoton2.setLayout(panelBoton2Layout);
        panelBoton2Layout.setHorizontalGroup(
            panelBoton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelBoton2Layout.setVerticalGroup(
            panelBoton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));

        panelBoton3.setBackground(new java.awt.Color(64, 60, 60));

        label3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("   3");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton3Layout = new javax.swing.GroupLayout(panelBoton3);
        panelBoton3.setLayout(panelBoton3Layout);
        panelBoton3Layout.setHorizontalGroup(
            panelBoton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelBoton3Layout.setVerticalGroup(
            panelBoton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        panelBoton1.setBackground(new java.awt.Color(64, 60, 60));

        label1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("   1");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton1Layout = new javax.swing.GroupLayout(panelBoton1);
        panelBoton1.setLayout(panelBoton1Layout);
        panelBoton1Layout.setHorizontalGroup(
            panelBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelBoton1Layout.setVerticalGroup(
            panelBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        panelBoton0.setBackground(new java.awt.Color(64, 60, 60));

        label0.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label0.setForeground(new java.awt.Color(255, 255, 255));
        label0.setText("   0");
        label0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton0Layout = new javax.swing.GroupLayout(panelBoton0);
        panelBoton0.setLayout(panelBoton0Layout);
        panelBoton0Layout.setHorizontalGroup(
            panelBoton0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label0, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelBoton0Layout.setVerticalGroup(
            panelBoton0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label0, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, -1, -1));

        panelBoton6.setBackground(new java.awt.Color(64, 60, 60));

        label6.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("   6");
        label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoton6Layout = new javax.swing.GroupLayout(panelBoton6);
        panelBoton6.setLayout(panelBoton6Layout);
        panelBoton6Layout.setHorizontalGroup(
            panelBoton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelBoton6Layout.setVerticalGroup(
            panelBoton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBoton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 80, 80));

        panelResta.setBackground(new java.awt.Color(64, 60, 60));

        labelResta.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelResta.setForeground(new java.awt.Color(255, 255, 255));
        labelResta.setText("   -");
        labelResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRestaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRestaLayout = new javax.swing.GroupLayout(panelResta);
        panelResta.setLayout(panelRestaLayout);
        panelRestaLayout.setHorizontalGroup(
            panelRestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelResta, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelRestaLayout.setVerticalGroup(
            panelRestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelResta, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        panelMultiplicacion.setBackground(new java.awt.Color(64, 60, 60));

        labelMultiplicacion.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelMultiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        labelMultiplicacion.setText("   x");
        labelMultiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMultiplicacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMultiplicacionLayout = new javax.swing.GroupLayout(panelMultiplicacion);
        panelMultiplicacion.setLayout(panelMultiplicacionLayout);
        panelMultiplicacionLayout.setHorizontalGroup(
            panelMultiplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelMultiplicacionLayout.setVerticalGroup(
            panelMultiplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        panelDivision.setBackground(new java.awt.Color(64, 60, 60));

        labelDivision.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelDivision.setForeground(new java.awt.Color(255, 255, 255));
        labelDivision.setText("   /");
        labelDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDivisionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDivisionLayout = new javax.swing.GroupLayout(panelDivision);
        panelDivision.setLayout(panelDivisionLayout);
        panelDivisionLayout.setHorizontalGroup(
            panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelDivisionLayout.setVerticalGroup(
            panelDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        panelSuma.setBackground(new java.awt.Color(64, 60, 60));

        labelSuma.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelSuma.setForeground(new java.awt.Color(255, 255, 255));
        labelSuma.setText("   +");
        labelSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSumaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSumaLayout = new javax.swing.GroupLayout(panelSuma);
        panelSuma.setLayout(panelSumaLayout);
        panelSumaLayout.setHorizontalGroup(
            panelSumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSumaLayout.setVerticalGroup(
            panelSumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSuma, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 80, 80));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Estos son los eventos, al momento de elegir un numero, esta aca su funcionalidad
    
    private void label7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseClicked
        //Imprime el numero 7 en el txtArea de nombre MostrarNumeros
        
        MostrarNumeros.append(numero.getN7());
        
        
        
        
    }//GEN-LAST:event_label7MouseClicked

    private void label8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseClicked
        //Imprime el numero 8 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN8());
        
        
    }//GEN-LAST:event_label8MouseClicked

    private void label9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MouseClicked
        //Imprime el numero 9 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN9());
        
        
        
    }//GEN-LAST:event_label9MouseClicked

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
        //Imprime el numero 4 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN4());
        
        
        
    }//GEN-LAST:event_label4MouseClicked

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        //Imprime el numero 5 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN5());
        
        
        
    }//GEN-LAST:event_label5MouseClicked

    private void label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseClicked
        //Imprime el numero 6 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN6());
        
        
        
    }//GEN-LAST:event_label6MouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        //Imprime el numero 1 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN1());
        
        
        
    }//GEN-LAST:event_label1MouseClicked

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        //Imprime el numero 2 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN2());
        
        
        
    }//GEN-LAST:event_label2MouseClicked

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
        //Imprime el numero 3 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN3());
        
        
        
    }//GEN-LAST:event_label3MouseClicked

    private void label0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label0MouseClicked
       //Imprime el numero 0 en el txtArea de nombre MostrarNumeros
        MostrarNumeros.append(numero.getN0());
        
        
        
    }//GEN-LAST:event_label0MouseClicked

    //Operacion de suma
    private void labelSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSumaMouseClicked
        //Imprime el signo de suma, en el txtArea de nombre MostrarNumeros
        num1 = Integer.parseInt(MostrarNumeros.getText()); //lo que hace es capturar el txtarea y lo almacena en la variable num1 de la clase AlmacenNumeros
        numero.setNum1(num1); 
        signo = "+"; //sera utilizado en el switch
        MostrarNumeros.setText("");//despues de haber almacenado las variables, lo que hace es poner en blanco el txtarea
        
        
    }//GEN-LAST:event_labelSumaMouseClicked

    //Operacion de resta
    private void labelRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRestaMouseClicked
        //Imprime el signo de resta, en el txtArea de nombre MostrarNumeros
        num1 = Integer.parseInt(MostrarNumeros.getText()); //lo que hace es capturar el txtarea y lo almacena en la variable num1 de la clase AlmacenNumeros
        numero.setNum1(num1); 
        signo = "-"; //sera utilizado en el switch
        MostrarNumeros.setText("");//despues de haber almacenado las variables, lo que hace es poner en blanco el txtarea
    }//GEN-LAST:event_labelRestaMouseClicked

    //Operacion de multiplicacion
    private void labelMultiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMultiplicacionMouseClicked
        //Imprime el signo de multiplicacion, en el txtArea de nombre MostrarNumeros
        num1 = Integer.parseInt(MostrarNumeros.getText()); //lo que hace es capturar el txtarea y lo almacena en la variable num1 de la clase AlmacenNumeros
        numero.setNum1(num1); 
        signo = "*"; //sera utilizado en el switch
        MostrarNumeros.setText("");//despues de haber almacenado las variables, lo que hace es poner en blanco el txtarea
    }//GEN-LAST:event_labelMultiplicacionMouseClicked

    //Operacion de division
    private void labelDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDivisionMouseClicked
        //Imprime el signo de division, en el txtArea de nombre MostrarNumeros
        num1 = Integer.parseInt(MostrarNumeros.getText()); //lo que hace es capturar el txtarea y lo almacena en la variable num1 de la clase AlmacenNumeros
        numero.setNum1(num1); 
        signo = "/"; //sera utilizado en el switch
        MostrarNumeros.setText("");//despues de haber almacenado las variables, lo que hace es poner en blanco el txtarea
    }//GEN-LAST:event_labelDivisionMouseClicked

    //Este evento devuelve el resultado de la operacion 
    private void labelResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelResultadoMouseClicked
        num2 = Integer.parseInt(MostrarNumeros.getText());//se puede ver que despues a ver capturado el num1, y selecionamos "resultado" toma los valores que hubieron en el txtarea
        //despues los guarda, lo que se observa es un cambio de string a entero
        numero.setNum2(num2);//almacen en num2
        switch (signo){
            //Lo que hace es presentar casos de signos, como un if, y resuelve la operacion
            case "+":
                
                MostrarNumeros.setText(Float.toString(num1+num2));
                
            case "-":
                MostrarNumeros.setText(Float.toString(num1+num2));
                break;
            case "*":
                MostrarNumeros.setText(Float.toString(num1*num2));
                break;
            case "/":
                MostrarNumeros.setText(Float.toString(num1/num2));
                break;
        
        }
    }//GEN-LAST:event_labelResultadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MostrarNumeros;
    private javax.swing.JPanel PanelBoton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel labelDivision;
    private javax.swing.JLabel labelMultiplicacion;
    private javax.swing.JLabel labelResta;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelSuma;
    private javax.swing.JPanel panelBoton0;
    private javax.swing.JPanel panelBoton1;
    private javax.swing.JPanel panelBoton2;
    private javax.swing.JPanel panelBoton3;
    private javax.swing.JPanel panelBoton4;
    private javax.swing.JPanel panelBoton5;
    private javax.swing.JPanel panelBoton6;
    private javax.swing.JPanel panelBoton8;
    private javax.swing.JPanel panelBoton9;
    private javax.swing.JPanel panelDivision;
    private javax.swing.JPanel panelMultiplicacion;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelResta;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JPanel panelSuma;
    // End of variables declaration//GEN-END:variables
}
